trigger:
  branches:
    include:
    - testBranch
variables:
  buildPlatform: x64
  imageName: windows-latest
  artifactName: Ideploy-drop123
  mavenOption: -Xmx3072m
  goals: package
  jdkVersion: 1.8
  pomPath: pom.xml
  contentsPath: '**/target/*.jar'
  testResultPath: ''
pool:
  vmImage: $(imageName)
steps:
- task: Maven@3
  inputs:
    mavenPomFile: $(pomPath)
    mavenOptions: $(mavenOption)
    javaHomeOption: JDKVersion
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: $(buildPlatform)
    publishJUnitResults: false
    goals: $(goals)
- task: CopyFiles@2
  inputs:
    SourceFolder: $(System.DefaultWorkingDirectory)
    Contents: $(contentsPath)
    TargetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    PathtoPublish: $(build.artifactstagingdirectory)
    ArtifactName: $(artifactName)
